### ISSUE TITLE
What is the license for this? 

### ISSUE THREAD

**Issue by tentamens** [stesim/godot-vehicle-sandbox#1]
this is a really cool project, but before I get ahead of myself I want to make sure you are fine with me using it as of right now there's no license

**Comment by stesim** [comment]
Hi, you're more than welcome to use the project if it's of any help to you and thanks for pointing out the missing license. I just added an MIT license file. Third-party assets used in the example have their own licensing terms, mostly Creative Commons 4.0 or similar, as documented in README.md or in text files next to the actual asset files.

**Comment by tentamens** [comment]
Great! thanks, one other question tho do you plan to add ABS soon? if not I may try and tackle that myself

**Comment by stesim** [comment]
Unfortunately, I don't have time to work on the project right now or in the near future. It served mostly self-educational purposes and I've made it public to serve as potential reference for anyone interested in working on their own vehicle implementation. New features, or the code clean-up that I really wanted to do, may or may not happen at some point in the future, depending on time and motivation to pick it up again.
